language: haskell
ghc:
  - 7.8
  - 7.6
  - 7.4

install:
  - cabal install --only-dependencies --enable-tests --enable-benchmarks

script:
  - cabal configure --enable-tests --enable-benchmarks && cabal build && cabal test && cabal bench && cat dist/test/*.log